### PR TITLE
Task Page Provider

### PR DESCRIPTION
**Pull request by guirenard**

### CODE REVIEW

**Comment by guirenard** [comment]
LGTM but as the user who created the PR, I cannot approve it :)

**Comment by nmpcunha** [comment]
WebUI side: https://github.com/nuxeo/nuxeo-web-ui/pull/800

**Comment by Gabez0r** [comment]
We should create a ticket to add unit tests for this element, probably refactoring those already done for `nuxeo-page-provider`.

**Comment by nmpcunha** [comment]
Indeed! Or, if we have room now, we can try to address during the execution of this ticket.

**Pull request merged**
