### PR TITLE
ELEMENTS-1175: fix checkbox behavior on nuxeo-data-table after polymer update

### PR DESCRIPTION
**Pull request by semisse**

### CODE REVIEW

**Review by richardsd — DISMISSED** [review]

**Review by nmpcunha — COMMENTED** [review]
My memory won't probably serve me well, since it was long time ago.
But, in any case, I think we've tried something similar at the time and we broke some other usage of `data-table` (not sure with or without the `checkmark`).

I would recommend you to take some time to test several usages of it 😉

**Review by mnixo — DISMISSED** [review]

**Review by andreacornaglia — COMMENTED** [review]
should we change the commit message to reflect the main goal of this fix? something like "fix checkbox behavior on nuxeo-data-table after polymer update"?

**Comment by semisse** [comment]
Yes we can, @andreacornaglia. Your suggestion is clearer. Thanks!

**Review by nmpcunha — COMMENTED** [review]
Looking to the existing JIRAS, it seems that the upgrade broke our CI, so it would be a great start: to ensure that our tests are passing.
But, in other to achieve that we'll need changes on WebUI side, right? The dependency is still "locked" there (https://github.com/nuxeo/nuxeo-web-ui/blob/master/package.json#L165).

Not sure if you done it locally, but we'll need to run the pipeline with changes on both repos. 😉

**Review by richardsd — APPROVED** [review]

**Review by mnixo — APPROVED** [review]

**Comment by semisse** [comment]
[Build ok with polymer dependancy unlocked  🎉 ](https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-sfialho/207/)
(cc @nmpcunha )

**Review by nmpcunha — COMMENTED** [review]
Glad to know that it works! 😉

**Comment by semisse** [comment]
the solution suggested here breaks the multiselection on nuxeo-datatable. We need to spend more time investigating this problem.

**Pull request closed without merging**
