### PR TITLE
ELEMENTS-1344: fully encode pdf preview url

### PR DESCRIPTION
**Pull request by michaelva**

### CODE REVIEW

**Comment by semisse** [comment]
Hello, Michaël, thank you so much for your contribution. Can I ask you to also backport this fix to 3.0.x? If you need any help, feel free to ping me.

**Review by richardsd — APPROVED** [review]

**Comment by Gabez0r** [comment]
Pipeline passed: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-pipeline/358/ 🔵

**Review by Gabez0r — APPROVED** [review]
@michaelva, could you please backport to the maintenance-3.0.x branch as well?

**Comment by michaelva** [comment]
Sure. I usually wait for the master PR to be approved before doing a backport to avoid confusion.

**Pull request merged**
