### PR TITLE
ELEMENTS-1359: clears the group suggestions input field on admin WEBU…

### PR DESCRIPTION
**Pull request by swarnadipa-dev**
…I every time the Add to Group button is clicked

### CODE REVIEW

**Review by Gabez0r — COMMENTED** [review]
Great work! The only recommendation I'd make would be to shorten the commit messages. At this point it is really hard to understand without clicking on each individual commit what it does:
image
Best practices recommend commit messages shorter than 80 characters, at least in the first line. You can add as many lines as you wish, with extra information. Here's an example: https://github.com/nuxeo/nuxeo-elements/commit/e9fadd1252a0a0bbc2e8959f9c69b1e059c049e5

**Comment by Gabez0r** [comment]
Also please amend your author information, which is pointing to `Global <global@DEL1-LMC-N77370.local>`. This is actually required to sign the CLA I think.

**Review by rakeshkumar1019 — COMMENTED** [review]
looks good

**Review by rakeshkumar1019 — DISMISSED** [review]

**Review by Gabez0r — DISMISSED** [review]

**Comment by Gabez0r** [comment]
Please do not forget to sign the CLA agreement.
image

**Review by Gabez0r — APPROVED** [review]

**Review by SnehalNaik-DEV — APPROVED** [review]
Looks good!

**Pull request merged**
