### PR TITLE
ELEMENTS-933: Pull up additional props from page provider element

### PR DESCRIPTION
**Pull request by vpasquier**

### CODE REVIEW

**Comment by Gabez0r** [comment]
Please, run this through Web UI pipeline to ensure that it doesn't break functional tests.

**Comment by nmpcunha** [comment]
You can access the pipeline using this _link_: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-pipeline/

Please let us know if you need further info.

**Comment by vpasquier** [comment]
I just gave up unfortunately because I cannot investigate on the random issues I got with this job... I will try to come back to it when I get time.

**Comment by Gabez0r** [comment]
We just landed a fix that should reduce the amount of randoms on the pipeline.

**Comment by nmpcunha** [comment]
I ran the pipeline: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-pipeline/267/

**Pull request merged**
