### PR TITLE
Elements-1698: Add focus to kebab menu options for comment when using keyboard

### PR DESCRIPTION
**Pull request by shadwal-sinha**
https://jira.nuxeo.com/browse/ELEMENTS-1698

### CODE REVIEW

**Review by swarnadipa-dev — COMMENTED** [review]
Please edit the description and add the JIRA ticket number.

**Review by rakeshkumar1019 — COMMENTED** [review]
Hardcoded English strings like 'edit' and 'delete' break internationalization.it will break in different language.

**Comment by swarnadipa-dev** [comment]
Branch name should be of the format "fix-<ticket-number>-small description"
No need to add 3.1.x at end

**Comment by rakeshkumar1019** [comment]
> Hardcoded English strings like 'edit' and 'delete' break internationalization.it will break in different language.

Ignore your code is right.

**Review by rakeshkumar1019 — APPROVED** [review]

**Review by swarnadipa-dev — APPROVED** [review]

**Review by arupmmi07 — APPROVED** [review]
Verified

**Pull request merged**
