### PR TITLE
ELEMENTS-1095: document icon sets available

### PR DESCRIPTION
**Pull request by bchauvin**
Document which material icon sets are available for nuxeo-operation-button

### CODE REVIEW

**Comment by bchauvin** [comment]
Source: https://nuxeo.slack.com/archives/C0FC1E6UD/p1574424537261000?thread_ts=1574385394.244000&cid=C0FC1E6UD

**Comment by Gabez0r** [comment]
Should we just rephrase the description of `icon` to something like "icon name, available from any of the loaded icon sets"?

**Comment by nelsonsilva** [comment]
IIRC there's ongoing work on the iconset editor which means that at some point we'll need to know which element properties are references to icon names. Perhaps we can start doing part of this work in Studio, flagging icon properties, and try to "inject" information about bundled iconsets in the documentation.

**Comment by bchauvin** [comment]
> I think this change doesn't make sense given that this element is not aware of what iconsets are loaded or not. The icon property can point to any icon of any of the iconsets that might be loaded by the application, including nuxeo-icons, which are missing on the list.

Alright, closing the PR, thanks.

@nelsonsilva That would be a big debate to have here, let's keep that for later ;-)

**Pull request closed without merging**
