### PR TITLE
ELEMENTS-1539: make search results loading in queue view and listing announced by screen reader

### PR DESCRIPTION
**Pull request by GuruprasadAnk1996**
https://jira.nuxeo.com/browse/ELEMENTS-1539

Please find the videos for reference
https://user-images.githubusercontent.com/107453632/201906606-c3d01307-46f1-4a88-be04-c02a70c72662.mov

https://user-images.githubusercontent.com/107453632/201906701-8cb32648-96d0-434e-ae0e-b97a10b2b1f4.mov

https://user-images.githubusercontent.com/107453632/201906651-c469910b-cfd4-40c4-9293-8e5d97531931.mov

https://user-images.githubusercontent.com/107453632/201906683-c37482f9-48d4-4ea9-91b7-7b4e323be80a.mov

### CODE REVIEW

**Review by Nisha-QA — APPROVED** [review]
Looks good

**Review by Nishant0928 — APPROVED** [review]

**Review by swarnadipa-dev — APPROVED** [review]
Looks good

**Review by rajatgoel-gl — APPROVED** [review]

**Comment by semisse** [comment]
Would it be possible to record a video showing the behaviour with voice over from mac?

**Comment by GuruprasadAnk1996** [comment]
> Would it be possible to record a video showing the behaviour with voice over from mac?

The videos have been shared in Slack, Kindly check and please review

**Review by semisse — APPROVED** [review]

**Pull request merged**
