### PR TITLE
ELEMENTS-916: remove preserve-white-space class on nuxeo-selectivity selected items

### PR DESCRIPTION
**Pull request by mnixo**
Proposed solution for [ELEMENTS-916](https://jira.nuxeo.com/browse/ELEMENTS-916).
Feedback would be greatly appreciated. Thank you!

### CODE REVIEW

**Comment by nmpcunha** [comment]
Thanks for the PR.
We can understand the issue faced, but we still have to consider the compatibility with: https://jira.nuxeo.com/browse/ELEMENTS-853

It would be nice to ensure that, at least, our functional tests are passing and then double check the referred ticket.

**Comment by nmpcunha** [comment]
Pipeline also ran without errors ([here](https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/128/). But, as mentioned, we'll need to look further to this specific topic since it may lead to a regression.

**Comment by mnixo** [comment]
I can confirm that this solution will reintroduce [ELEMENTS-853](https://jira.nuxeo.com/browse/ELEMENTS-853). I will rework the solution to avoid that.

**Comment by mnixo** [comment]
I added a new commit to wrap the formatting of labels with:
`<span class="preserve-white-space"></span>`

I still vote for the removal of the enforcing of the `preserve-white-space` at the `<nuxeo-selectivity>` level ([first commit](https://github.com/nuxeo/nuxeo-elements/pull/63/commits/ce1891d21ba0e8b21731de9f2b29b3df4d5a56e8)) as it makes it hard to work around the unavoidable `white-space: pre;` CSS rule (on the results).
Instead, I think that for the use cases for which the constraint is needed, it can be added directly in the results/selection formatter.
The [last commit](https://github.com/nuxeo/nuxeo-elements/pull/63/commits/4c13b8c2adc773223028a9db2e4b3a64e50fbabd) I added does just that for `<nuxeo-user-management>`, but we still need to verify if it is needed on other usages of `<nuxeo-selectivity>`.

Using `class="preserve-white-space"` outside `<nuxeo-selectivity>` can be a bit weird, but it still better than using `<span style="white-space:pre;">...</span>`.

**Comment by Gabez0r** [comment]
👍

**Comment by nmpcunha** [comment]
👍

**Pull request merged**
