### PR TITLE
ELEMENTS-1382: fix configuration boolean property parsing

### PR DESCRIPTION
**Pull request by richardsd**

### CODE REVIEW

**Comment by richardsd** [comment]
Legacy pipeline here https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-rdias/106/ ⏳

**Review by mnixo — APPROVED** [review]

**Review by Gabez0r — APPROVED** [review]

**Comment by Gabez0r** [comment]
Please don't forget to backport it to 3.0.x.

**Comment by richardsd** [comment]
> Please don't forget to backport it to 3.0.x.

I'll open the PR for the backport in the meantime. Thank you.

**Comment by Gabez0r** [comment]
And thank you so much for the tests! 👏 💪

**Pull request merged**
