### PR TITLE
ELEMENTS-1266: lock @open-wc/testing-helpers dependency

### PR DESCRIPTION
**Pull request by semisse**

### CODE REVIEW

**Review by mnixo — DISMISSED** [review]

**Review by nmpcunha — COMMENTED** [review]
As we discussed, I'm not totally sure about this change. I understand that it solves your issue, but we are locking to a version released 7 months ago... Since we are using semver, we were already using `1.8.10` for more than a month 🤔 

This to say that I can understand that it may solve/hide the issue, but it doesn't seem to be "the thing"

**Comment by semisse** [comment]
> As we discussed, I'm not totally sure about this change. I understand that it solves your issue, but we are locking to a version released 7 months ago... Since we are using semver, we were already using successfully`1.8.10` for more than a month 🤔
> 
> This to say that I can understand that it may solve/hide the issue, but it doesn't seem to be "the thing"

It breaks after upgrading to 1.8. Locked it at 1.7.2

**Review by mnixo — DISMISSED** [review]

**Review by nmpcunha — APPROVED** [review]
Please make sure a ticket is created to revert this change.
They should be releasing the fix soon: https://github.com/open-wc/open-wc/commit/046668936986c3bc293074065651592e14199497#diff-c416e077a44000ab8db0a0dc526c0705096002492abc02407f0c671291365bfa

**Comment by semisse** [comment]
Locked the version only at storybook level, as suggested by @Gabez0r (thanks)

**Review by mnixo — APPROVED** [review]

**Review by Gabez0r — APPROVED** [review]
Please create a followup cleanup ticket to revert this. :pray:.

**Pull request merged**
