### PR TITLE
NXP-26859: Add query parameter

### PR DESCRIPTION
**Pull request by akervern**

### CODE REVIEW

**Comment by nmpcunha** [comment]
👍

**Comment by nmpcunha** [comment]
Small note: we usually use lower case, i.e. "NXP-26859: add..."

**Comment by semisse** [comment]
👍

**Comment by akervern** [comment]
Commit message updated; kept branch naming for follow up purpose! :)

**Comment by Gabez0r** [comment]
👍

**Comment by nmpcunha** [comment]
👍

**Pull request merged**
