### PR TITLE
ELEMENTS-919: allow new entries in nuxeo-selectivity when using data instead of operation

### PR DESCRIPTION
**Pull request by mnixo**
Proposed solution for [ELEMENTS-919](https://jira.nuxeo.com/browse/ELEMENTS-919).
Feedback would be greatly appreciated. Thank you!

### CODE REVIEW

**Comment by nmpcunha** [comment]
Pipeline ran without problems ([see here](https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/127/))

**Comment by Gabez0r** [comment]
Pipeline OK: https://qa.nuxeo.org/jenkins/view/All/job/web-ui-pipeline-gbarata/144/

**Comment by Gabez0r** [comment]
👍

**Comment by guirenard** [comment]
:+1:

**Comment by nmpcunha** [comment]
👍

**Pull request merged**
