### PR TITLE
ELEMENTS-1520: edition of a comment containing non-alpha-numeric char…

### PR DESCRIPTION
**Pull request by rakeshkumar1019**
https://jira.nuxeo.com/browse/ELEMENTS-1520

### CODE REVIEW

**Review by swarnadipa-dev — APPROVED** [review]
Looks good

**Review by SnehalNaik-DEV — DISMISSED** [review]
Looks Good.

**Review by swarnadipa-dev — DISMISSED** [review]
Looks good

**Review by richardsd — DISMISSED** [review]

**Review by GuruprasadAnk1996 — DISMISSED** [review]

**Review by poonamyadav252 — DISMISSED** [review]

**Review by Gabez0r — COMMENTED** [review]
I don't see this change in this PR: https://github.com/nuxeo/nuxeo-web-ui/pull/1588/files#diff-eec05571301579a60f4c845f25787a80038ddcbf3e7112de4862da825823eaf8R277

Is this intended?

**Comment by rakeshkumar1019** [comment]
> I don't see this change in this PR: https://github.com/nuxeo/nuxeo-web-ui/pull/1588/files#diff-eec05571301579a60f4c845f25787a80038ddcbf3e7112de4862da825823eaf8R277
> 
> Is this intended?

yes,but now i'm trying another approach to solve this issue. Exactly like i did in  above `10.10`.
https://github.com/nuxeo/nuxeo-elements/blob/maintenance-3.0.x/ui/nuxeo-document-comments/nuxeo-document-comment-thread.js#L262

**Comment by rakeshkumar1019** [comment]
> I don't see this change in this PR: https://github.com/nuxeo/nuxeo-web-ui/pull/1588/files#diff-eec05571301579a60f4c845f25787a80038ddcbf3e7112de4862da825823eaf8R277
> 
> Is this intended?

@Gabez0r, My approach, as mentioned in the previous comment, was incorrect. I've incorporated the changes from [10.10](https://github.com/nuxeo/nuxeo-web-ui/pull/1588/files#diff-eec05571301579a60f4c845f25787a80038ddcbf3e7112de4862da825823eaf8R277) that you mentioned in your previous comment.
Thank you.

**Review by swarnadipa-dev — APPROVED** [review]
Looks good

**Review by richardsd — APPROVED** [review]

**Review by GuruprasadAnk1996 — APPROVED** [review]

**Pull request merged**
