### PR TITLE
ELEMENTS-1512 - startDate = endDate Permission for Elements

### PR DESCRIPTION
**Pull request by poonamyadav252**

### CODE REVIEW

**Review by richardsd — DISMISSED** [review]
Looks good to me 👍 Nice work

**Review by rakeshkumar1019 — CHANGES_REQUESTED** [review]
commit message format:
`<ticket number>: <description> `
In this case it will be `ELEMENTS-1512: modified permission’s end date`
Note: 

- description starts with small letter.
- description should be in present tense.

**Comment by semisse** [comment]
Please check @rakeshkumar1019 comment; also don't forget to sign the CLA.

**Comment by richardsd** [comment]
> Please check @rakeshkumar1019 comment; also don't forget to sign the CLA.

Please don't forge to sign the CLA.

**Comment by richardsd** [comment]
> > Please check @rakeshkumar1019 comment; also don't forget to sign the CLA.
> 
> Please don't forge to sign the CLA.

And please don't forget that you need to reword your commit on this PR as well, similar to what you did for the `10.10` PR

**Review by semisse — DISMISSED** [review]
Your commit message is still not following the correct format.
Please refer to Rakesh comment and his suggestion.

**Review by swarnadipa-dev — APPROVED** [review]
Looks good

**Review by rakeshkumar1019 — APPROVED** [review]

**Review by richardsd — APPROVED** [review]

**Review by Gabez0r — APPROVED** [review]

**Pull request merged**
